<center><h5.5> masking age <18  and >45

In [1]:
import numpy as np
ages = np.array([45, 67, 89, 23, 56, 90, 78, 92, 51, 64])

ages[(ages>45) | (ages<18)]=0

In [2]:
ages

array([45,  0,  0, 23,  0,  0,  0,  0,  0,  0])

In [1]:
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
slicing = matrix[::2, :-3:-1] 
print(slicing)

[[ 4  3]
 [12 11]]


In [2]:
matrix.shape

(3, 4)

In [3]:
                                    # Flattening the array based on Dimensions
sales_data = np.array([[200, 300, 400], 
                       [150, 250, 350], 
                       [100, 200, 300]])

# Flatten the array if it is 2D
if sales_data.shape == (3,3):
    flatten = sales_data.flatten()
    print(flatten) 

[200 300 400 150 250 350 100 200 300]


In [9]:
                                    # converting Numpy Array to Python List
sales_data = np.array([200,300,400,500,600])

list1 = sales_data.tolist()                 # tolist() converts thw array to list
print(list1)
print("Data type of sales data",type(sales_data))
print("Data type of converted list", type(list1))

[200, 300, 400, 500, 600]
Data type of sales data <class 'numpy.ndarray'>
Data type of converted list <class 'list'>


In [10]:
                                        # Scaler Matrix with diagonal element 8

# Create a scalar matrix of size 3x3 with diagonal elements as 8
matrix = np.eye(3,3, dtype= int)
print(matrix * 8)

[[8 0 0]
 [0 8 0]
 [0 0 8]]


In [11]:
                                        # Cheking row existance in an array
sales_data = np.array([[200, 400, 300],
                       [300, 500, 400],
                       [500, 600, 700],
                       [100, 200, 300]])

row_to_check = [300, 500, 400]

# Write your code here
if row_to_check in sales_data[:]:
    print("Row is present.")
else:
    print("Row is not present")

Row is present.


In [ ]:
                                        # Tuple to Array(change data type of array to float)
num_tuple = ('1', '2', '3', '4')

# Write your code here
list1 = []
for char in num_tuple:
    list1.append(float(char))

print(np.array((list1)))

[1. 2. 3. 4.]


In [13]:
                                        # Replacing Negatives in array 
temperature_data = np.array([10, -5, 30, -2, 45, -12, 60])

# Replace negative values with their positive counterpart
update = []
for num in temperature_data:
    update.append(abs(num))
print(np.array((update)))

[10  5 30  2 45 12 60]


In [14]:
#Also 
temperature_data = np.array([10, -5, 30, -2, 45, -12, 60])
result = np.abs(temperature_data)
print(result)

[10  5 30  2 45 12 60]


In [16]:
                                                # Salary Adjustment

salaries = np.full((5,10), 50000.0)             # % departments 10 employees each
salaries[0] *= 1.10                             # Increase salary by 10% for employees in department 1.
salaries[2] *= 0.95                             # Decrease salary by 5% for employees in department 3.

total_salaries = np.sum(salaries, axis = 1)         # sum across row
average_salaries= np.mean(salaries , axis = 1)  # mean across row

print("Total salary for each department:",total_salaries)
print("Average salary for each department:",average_salaries)     

Total salary for each department: [550000. 500000. 475000. 500000. 500000.]
Average salary for each department: [55000. 50000. 47500. 50000. 50000.]


In [17]:
                                                    # Highest marks of student

marks_data = np.array([[85, 90, 88],
                       [75, 80, 78],
                       [92, 95, 91],
                       [60, 65, 70]])

# Find the highest marks for each student (each row)
maxi = np.max(marks_data ,axis = 1)
print(maxi)

[90 80 95 70]


In [19]:
                                                    # Frequency of Unique Elements
# Array representing the scores of students
scores = np.array([85, 90, 85, 70, 95, 90, 85, 70, 80, 95])

# Calculate the frequency of each unique score

unique_num, counts = np.unique(scores, return_counts= True)     # identifies every distinct score and counts how many times each one appears.
print(unique_num)
print(counts)

[70 80 85 90 95]
[2 1 3 2 2]


In [20]:
                                                # Blank RGB Image Array
RGB_image = np.full((500,500,3), 0)
print(RGB_image.shape)

# also

# Dimensions: (Height, Width, Channels)
blank_canvas = np.zeros((500, 500, 3), dtype=np.uint8)

# Display the shape of the array
print(blank_canvas.shape)

(500, 500, 3)
(500, 500, 3)


In [ ]:
                                                    # Pattern in Numpy 7x7( set main diagonal and anti-diagonal elements as 1)

matrix  = np.eye(7, dtype =int)
for i in range(7):
    matrix[i, 6-i] = 1

print(matrix)

[[1 0 0 0 0 0 1]
 [0 1 0 0 0 1 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 0 0 1 0]
 [1 0 0 0 0 0 1]]


In [22]:
# also
# Create a 7x7 matrix of zeros
size = 7
matrix = np.zeros((size, size), dtype=int)

# Fill the main diagonal with 1
# np.diag_indices returns the indices for the main diagonal
matrix[np.diag_indices(size)] = 1

# Fill the anti-diagonal with 1
# np.fliplr flips the array horizontally, allowing us to target the anti-diagonal
# We use indexing to flip the identity-like logic
matrix[np.arange(size), np.arange(size-1, -1, -1)] = 1

# Display the resulting matrix
print(matrix)

[[1 0 0 0 0 0 1]
 [0 1 0 0 0 1 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 0 0 1 0]
 [1 0 0 0 0 0 1]]


In [23]:
                                                # Matrix Operations (R = (A.B.T) + concat(C,D))

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[1, 1],
              [2, 2],
              [3, 3]])

D = np.array([[0],
              [1],
              [2]])

# Write your code here
result = np.dot(A, B.T) + np.concatenate((C,D), axis= 1)
print(result) 

[[ 47  29  10]
 [120  75  29]
 [193 121  48]]
