<center><h5.5> masking age <18  and >45

In [1]:
import numpy as np
ages = np.array([45, 67, 89, 23, 56, 90, 78, 92, 51, 64])

ages[(ages>45) | (ages<18)]=0

In [2]:
ages

array([45,  0,  0, 23,  0,  0,  0,  0,  0,  0])

In [1]:
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
slicing = matrix[::2, :-3:-1] 
print(slicing)

[[ 4  3]
 [12 11]]


In [2]:
matrix.shape

(3, 4)

In [3]:
                                    # Flattening the array based on Dimensions
sales_data = np.array([[200, 300, 400], 
                       [150, 250, 350], 
                       [100, 200, 300]])

# Flatten the array if it is 2D
if sales_data.shape == (3,3):
    flatten = sales_data.flatten()
    print(flatten) 

[200 300 400 150 250 350 100 200 300]


In [9]:
                                    # converting Numpy Array to Python List
sales_data = np.array([200,300,400,500,600])

list1 = sales_data.tolist()                 # tolist() converts thw array to list
print(list1)
print("Data type of sales data",type(sales_data))
print("Data type of converted list", type(list1))

[200, 300, 400, 500, 600]
Data type of sales data <class 'numpy.ndarray'>
Data type of converted list <class 'list'>


In [10]:
                                        # Scaler Matrix with diagonal element 8

# Create a scalar matrix of size 3x3 with diagonal elements as 8
matrix = np.eye(3,3, dtype= int)
print(matrix * 8)

[[8 0 0]
 [0 8 0]
 [0 0 8]]


In [11]:
                                        # Cheking row existance in an array
sales_data = np.array([[200, 400, 300],
                       [300, 500, 400],
                       [500, 600, 700],
                       [100, 200, 300]])

row_to_check = [300, 500, 400]

# Write your code here
if row_to_check in sales_data[:]:
    print("Row is present.")
else:
    print("Row is not present")

Row is present.


In [ ]:
                                        # Tuple to Array(change data type of array to float)
num_tuple = ('1', '2', '3', '4')

# Write your code here
list1 = []
for char in num_tuple:
    list1.append(float(char))

print(np.array((list1)))

[1. 2. 3. 4.]


In [13]:
                                        # Replacing Negatives in array 
temperature_data = np.array([10, -5, 30, -2, 45, -12, 60])

# Replace negative values with their positive counterpart
update = []
for num in temperature_data:
    update.append(abs(num))
print(np.array((update)))

[10  5 30  2 45 12 60]


In [14]:
#Also 
temperature_data = np.array([10, -5, 30, -2, 45, -12, 60])
result = np.abs(temperature_data)
print(result)

[10  5 30  2 45 12 60]
