In [1]:
import numpy as np

In [2]:
list1= [1,2,3,4,5,6]
array= np.array(list1)

In [3]:
type(array)

numpy.ndarray

In [4]:
print(array)

[1 2 3 4 5 6]


<h5> Execution time Difference 

In [1]:
import time

In [11]:
start = time.time()
output_list = [i*2 for i in range(1000000)]
end = time.time()

print("time to excecute the operation was", end-start)

time to excecute the operation was 0.06490588188171387


In [4]:
import numpy as np

In [12]:
start = time.time()
output_arr = np.arange(1000000) *2
end= time.time()

print("time to execute array operation using Numpy is:",end-start)

time to execute array operation using Numpy is: 0.006562232971191406


<h6> <center> Array from a List and a Tuple 

In [13]:
# Array from Tuple and List
array1 = np.array([1,2,4,3,5])
print(array1)

array2 = np.array((1,2,3,4,5))
print(array2)


[1 2 4 3 5]
[1 2 3 4 5]


<h6><center> 1-D, 2-D and 3-D Array

In [14]:
#1-D
array1 = np.array([4,5,6,7,8])
print("This is 1-D array", array1)

This is 1-D array [4 5 6 7 8]


In [17]:
#2-D
array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("This is 2-D array", array_2D, sep= '\n')

This is 2-D array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
len(array_2D)           # only 3 elements , which can also mean 3 rows

3

In [ ]:
array_2D.dtype          # int64 means its data type is of integer with 64 bit

dtype('int64')

In [ ]:
array_2D.ndim           # represents the dimensionality of the array

2

In [21]:
array_2D = np.array([[1,2],[3,4]],dtype = 'int32')      # apart from default 64 bit,we can set the 32 bit value to integer 
print(array_2D)

[[1 2]
 [3 4]]


In [22]:
array_2D.dtype

dtype('int32')

In [ ]:
array_2D.shape                          # returns the size of array

(2, 2)

In [ ]:
array_2D.size                           # returns  the size or no. of elements it have

4

In [ ]:
array5 =np.array([[1,2,3],[2,3]])           # this isnt allowed 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#3-D
array_3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])             # stack of 2-d array forms 3-D array
print("This is our 3-D array:",array_3D,sep='\n')

This is our 3-D array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
array_3D.shape          # 3(we have three 2-D arrays), 2(we have two 1-D arrays) and 2(means 1-D array have 2 elements)

(3, 2, 2)

<h6> <center> Indexing and Slicing

In [ ]:
print(array_2D[1,0])            # will return first element of second row
print(array_2D[1][0])           # both the ways work same 

3
3


In [ ]:
print(array_3D[2,1,1])              # access the 2nd element from 2nd row of third row 
print(array_3D[2][1][1])

12
12


In [37]:
print(array_2D[1,:])                # access the whole second row
print(array_2D[0][:])

[3 4]
[1 2]


In [41]:
print(array_3D[1,:,0:2])          # access the 2nd row column of 3d array
print(array_3D[1][:][:])


[[5 6]
 [7 8]]
[[5 6]
 [7 8]]


In [ ]:
# picking 2nd row from all slices
print(array_3D[ : ,1 , :])          # 3 4  7 8  11 12

[[ 3  4]
 [ 7  8]
 [11 12]]


In [ ]:
import numpy as np
data = np.array([1.0, 2.9, 9+4j])
print(type(data[1]))                        # When we create array with mixed types, it promotes the entire array to the most general type.

<class 'numpy.complex128'>


In [ ]:
arr = np.array([10,15,20,25,30,35,40])
mask = arr%10==0                        # generates boolean array [True, False, True, .......]
result= arr[mask]                       # filters out elements where mask is True
print(result)

[10 20 30 40]


In [3]:
matrix_x = np.array([[10,20,30,40],[15,25,35,45],[12,24,36,48]])
matrix_y= matrix_x
print(matrix_y is matrix_x)

True


In [ ]:
# converting float list to numpy array of integer type
my_list = [1.2, 3.4, 6.9]
array_int = np.array(my_list , dtype = 'int')
print(array_int)

[1 3 6]


In [ ]:
# analyze the memory consumption
my_array = np.array([10,40,50,60,80])
print("Item Size",my_array.itemsize)                # 8 byte, returns the total memory consumption
print("Size of array",my_array.size)                # 5 elements
print("total Memory", my_array.nbytes,"bytes")      # 8*5 , 40 bytes

Item Size 8
Size of array 5
total Memory 40 bytes


In [18]:
# getting raw buffer from numpy array 
print(my_array.data)                # memory where actual data of numpy array is stored

In [19]:
# Arithmatic Operations on NumPy arrays
array1 = np.array([10, 20, 30])
array2 = np.array([2, 5, 10])

add  =array1 + array2
sub = array1 - array2
mul = array1 * array2
div = array1 / array2
print(f"Addition: {add}")
print(f"Subtraction: {sub}")
print(f"Multiplication: {mul}")
print(f"Division: {div}")


Addition: [12 25 40]
Subtraction: [ 8 15 20]
Multiplication: [ 20 100 300]
Division: [5. 4. 3.]


In [20]:
data = np.array([[25, 180, 75], 
                 [30, 175, 68], 
                 [35, 170, 70], 
                 [40, 165, 80]])

# 1. Extract the first two rows and the first two columns
subarray = data[0:2 ,0:2]
print("Extracted 2x2 Subarray:")
print(subarray)

# 2. Extract the last row of the array
last_row = data[3]
print(f"Last Row: {last_row}")

# 3. Extract all rows but only the second column
second_column = data[:,1]
print(f"Second Column: {second_column}")

Extracted 2x2 Subarray:
[[ 25 180]
 [ 30 175]]
Last Row: [ 40 165  80]
Second Column: [180 175 170 165]


In [21]:
# determine Number of dimensions for image stored(grayscale 2D, colour 3D)
Image = np.array([[0, 255, 128], 
                 [64, 32, 16]])

# Finding dimensions
dimension = Image.ndim
if dimension==3:
    print("Colored Image")
elif dimension ==2:
    print("Grayscale Image")
else:
    pass

Grayscale Image


In [22]:
dataset = np.array([[[1, 2], [3, 4]], 
                     [[5, 6], [7, 8]]])

# Calculate rows and columns
row_col = dataset.shape
# Calculate total number of elements present in the dataset
no_of_elements = dataset.size

# Print results
print(f"Rows & Columns in the dataset: {row_col}")
print(f"Number of Elements in the dataset: {no_of_elements}")

Rows & Columns in the dataset: (2, 2, 2)
Number of Elements in the dataset: 8


In [23]:
# Dictionary to numpy Array
data = {
    "Temperature": 35,
    "Humidity": 75,
    "Pressure": 1013,
    "WindSpeed": 12
}

# Extracting keys and converting to a NumPy array
keys_array = np.array(list(data.keys()))

print("Array of keys:", keys_array)

Array of keys: ['Temperature' 'Humidity' 'Pressure' 'WindSpeed']


In [26]:
# weather temperature filtering

temperatures = np.array([
    25, 32, 29, 35, 28, 31, 30, 27, 33, 34, 26, 29, 30, 32, 33, 
    36, 28, 31, 30, 29, 35, 27, 28, 31, 34, 30, 29, 32, 35, 28, 
    33, 26, 29, 30, 34, 32, 36, 28, 31, 30, 29, 33, 28, 30, 31, 
    32, 34, 29, 27, 35, 31, 30, 28, 33, 34, 36, 29, 31, 30, 29, 
    35, 28, 32, 30, 27, 33, 34, 28, 29, 32, 31, 30, 27, 35, 29, 
    30, 32, 34, 31, 28, 33, 30, 29, 32, 36, 28, 35, 30, 29, 31, 
    34, 32, 33, 28, 30, 29
])

# Define the threshold
threshold = 35

# Mask indexing to filter temperatures
filtered_temperatures = temperatures[temperatures>threshold]

print(f"Filtered temperatures greater than {threshold}°C:", filtered_temperatures)

Filtered temperatures greater than 35°C: [36 36 36 36]
