In [1]:
import numpy as np

In [2]:
list1= [1,2,3,4,5,6]
array= np.array(list1)

In [3]:
type(array)

numpy.ndarray

In [4]:
print(array)

[1 2 3 4 5 6]


<h5> Execution time Difference 

In [1]:
import time

In [11]:
start = time.time()
output_list = [i*2 for i in range(1000000)]
end = time.time()

print("time to excecute the operation was", end-start)

time to excecute the operation was 0.06490588188171387


In [4]:
import numpy as np

In [12]:
start = time.time()
output_arr = np.arange(1000000) *2
end= time.time()

print("time to execute array operation using Numpy is:",end-start)

time to execute array operation using Numpy is: 0.006562232971191406


<h6> <center> Array from a List and a Tuple 

In [13]:
# Array from Tuple and List
array1 = np.array([1,2,4,3,5])
print(array1)

array2 = np.array((1,2,3,4,5))
print(array2)


[1 2 4 3 5]
[1 2 3 4 5]


<h6><center> 1-D, 2-D and 3-D Array

In [14]:
#1-D
array1 = np.array([4,5,6,7,8])
print("This is 1-D array", array1)

This is 1-D array [4 5 6 7 8]


In [17]:
#2-D
array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("This is 2-D array", array_2D, sep= '\n')

This is 2-D array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
len(array_2D)           # only 3 elements , which can also mean 3 rows

3

In [ ]:
array_2D.dtype          # int64 means its data type is of integer with 64 bit

dtype('int64')

In [ ]:
array_2D.ndim           # represents the dimensionality of the array

2

In [21]:
array_2D = np.array([[1,2],[3,4]],dtype = 'int32')      # apart from default 64 bit,we can set the 32 bit value to integer 
print(array_2D)

[[1 2]
 [3 4]]


In [22]:
array_2D.dtype

dtype('int32')

In [ ]:
array_2D.shape                          # returns the size of array

(2, 2)

In [ ]:
array_2D.size                           # returns  the size or no. of elements it have

4

In [ ]:
array5 =np.array([[1,2,3],[2,3]])           # this isnt allowed 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#3-D
array_3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])             # stack of 2-d array forms 3-D array
print("This is our 3-D array:",array_3D,sep='\n')

This is our 3-D array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
array_3D.shape          # 3(we have three 2-D arrays), 2(we have two 1-D arrays) and 2(means 1-D array have 2 elements)

(3, 2, 2)

<h6> <center> Indexing and Slicing

In [ ]:
print(array_2D[1,0])            # will return first element of second row
print(array_2D[1][0])           # both the ways work same 

3
3


In [ ]:
print(array_3D[2,1,1])              # access the 2nd element from 2nd row of third row 
print(array_3D[2][1][1])

12
12


In [37]:
print(array_2D[1,:])                # access the whole second row
print(array_2D[0][:])

[3 4]
[1 2]


In [41]:
print(array_3D[1,:,0:2])          # access the 2nd row column of 3d array
print(array_3D[1][:][:])


[[5 6]
 [7 8]]
[[5 6]
 [7 8]]


In [ ]:
# picking 2nd row from all slices
print(array_3D[ : ,1 , :])          # 3 4  7 8  11 12

[[ 3  4]
 [ 7  8]
 [11 12]]
