In [3]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('array before transpose',arr)
print('array after transpose',arr.transpose())

array before transpose [[1 2 3]
 [4 5 6]
 [7 8 9]]
array after transpose [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# also shorthand way
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
arr1 = np.array([6,2,3,4,7,5,1])                  # 1D array
arr2 = np.array([[3,1,2],[4,6,5],[9,7,8]])      # 2D array
arr3 = np.array([[[1,3,2],[6,5,4],[7,9,8]],[[12,11,13],[23,22,21],[33,32,31]]])     # 3D array

sorted_arr1 = np.sort(arr1)
print("sorted 1D array: ",sorted_arr1)

sorted_arr2 = np.sort(arr2, axis =1)        # sorts horizontally
print("2D array sorted horizontally:", sorted_arr2, sep ='\n')

sorted_arr2_vert = np.sort(arr2, axis = 0)  # sorts vertically
print("2D array sorted Vertically:", sorted_arr2_vert, sep='\n')

sorted_arr3 =np.sort(arr3 ,axis =2)             # axis(2)sorts along third dimension(column)
print("3D array sorted horizontally:",sorted_arr3)

sorted_arr3_vert = np.sort(arr3, axis =1)       # along column
print("3D array sorted vertically:",sorted_arr3_vert)

sorted 1D array:  [1 2 3 4 5 6 7]
2D array sorted horizontally:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2D array sorted Vertically:
[[3 1 2]
 [4 6 5]
 [9 7 8]]
3D array sorted horizontally: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [21 22 23]
  [31 32 33]]]
3D array sorted vertically: [[[ 1  3  2]
  [ 6  5  4]
  [ 7  9  8]]

 [[12 11 13]
  [23 22 21]
  [33 32 31]]]
