<h5><center> Transpose of an array

In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('array before transpose',arr)
print('array after transpose',arr.transpose())

array before transpose [[1 2 3]
 [4 5 6]
 [7 8 9]]
array after transpose [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
# also shorthand way
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


<h5><center> Sorting 

In [4]:
arr1 = np.array([6,2,3,4,7,5,1])                  # 1D array
arr2 = np.array([[3,1,2],[4,6,5],[9,7,8]])      # 2D array
arr3 = np.array([[[1,3,2],[6,5,4],[7,9,8]],[[12,11,13],[23,22,21],[33,32,31]]])     # 3D array

sorted_arr1 = np.sort(arr1)
print("sorted 1D array: ",sorted_arr1)

sorted_arr2 = np.sort(arr2, axis =1)        # sorts horizontally
print("2D array sorted horizontally:", sorted_arr2, sep ='\n')

sorted_arr2_vert = np.sort(arr2, axis = 0)  # sorts vertically
print("2D array sorted Vertically:", sorted_arr2_vert, sep='\n')

sorted_arr3 =np.sort(arr3 ,axis =2)             # axis(2)sorts along third dimension(column)
print("3D array sorted horizontally:",sorted_arr3)

sorted_arr3_vert = np.sort(arr3, axis =1)       # along column
print("3D array sorted vertically:",sorted_arr3_vert)

sorted 1D array:  [1 2 3 4 5 6 7]
2D array sorted horizontally:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2D array sorted Vertically:
[[3 1 2]
 [4 6 5]
 [9 7 8]]
3D array sorted horizontally: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [21 22 23]
  [31 32 33]]]
3D array sorted vertically: [[[ 1  3  2]
  [ 6  5  4]
  [ 7  9  8]]

 [[12 11 13]
  [23 22 21]
  [33 32 31]]]


In [5]:
# sorting in reverse order with indexing (horizontally)
sorted_arr2[: , : :-1]  

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [7]:
# sorting array in reverse order with indexing (Vertically)
sorted_arr2[ : :-1 ,:]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [13]:
print("sorted 2D  array:", sorted_arr2)
print("sorted Array in Descending order ",np.flip(sorted_arr2, axis =0), sep = "\n")             

sorted 2D  array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
sorted Array in Descending order 
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [17]:
# argsort ( returns sorted array index)
arr1 =np.array([50,55,44,12,95,34,65,32,12])
indices = np.argsort(arr1) 

print("normal array" ,arr1)
print("Indices of sorted array", indices)

print("sorted array using Indices",arr1[indices])

normal array [50 55 44 12 95 34 65 32 12]
Indices of sorted array [3 8 7 5 2 0 1 6 4]
sorted array using Indices [12 12 32 34 44 50 55 65 95]


In [26]:
arr2 = np.array([[12,45,23],[33,88,21],[61,57,46]])
print('Given 2D array is', arr2,sep='\n')

indices1 = np.argsort(arr2 , axis = 1)           # row wise
print("\nRow wise sorted indices are:",indices1,sep ='\n')
print("row-wisee sorted array is:" , np.take_along_axis(arr2, indices1 , axis =1), sep ='\n')

indices2 = np.argsort(arr2 , axis =0)            # column wise
print("\nColumn wise sorted indices are:", indices2)
print("column-wise sorted array is:",np.take_along_axis(arr2, indices2 , axis =0), sep='\n')



Given 2D array is
[[12 45 23]
 [33 88 21]
 [61 57 46]]

Row wise sorted indices are:
[[0 2 1]
 [2 0 1]
 [2 1 0]]
row-wisee sorted array is:
[[12 23 45]
 [21 33 88]
 [46 57 61]]

Column wise sorted indices are: [[0 0 1]
 [1 2 0]
 [2 1 2]]
column-wise sorted array is:
[[12 45 21]
 [33 57 23]
 [61 88 46]]


<h5><center> Concatenate

In [27]:
arr1 = np.array([3,2,1])
arr2 = np.array([6,9,4])

result =np.concatenate((arr1, arr2))
print("concatenated 1D array ", result)

concatenated 1D array  [3 2 1 6 9 4]


In [30]:
arr1 = np.array([[45,23,2,56,7],[78,655,42,3,942],[45,325,99,361,5]])
arr2 = np.array([[56,12,91,73,65],[56,74,32,53,41],[23,75,86,74,63]])

result1 = np.concatenate((arr1, arr2), axis=1)              # along row
print("2D array concatenated along rows \n", result1)

result2  = np.concatenate((arr1, arr2), axis=0)              # along column
print("2D array concatenated along columns \n", result2)

2D array concatenated along rows 
 [[ 45  23   2  56   7  56  12  91  73  65]
 [ 78 655  42   3 942  56  74  32  53  41]
 [ 45 325  99 361   5  23  75  86  74  63]]
2D array concatenated along columns 
 [[ 45  23   2  56   7]
 [ 78 655  42   3 942]
 [ 45 325  99 361   5]
 [ 56  12  91  73  65]
 [ 56  74  32  53  41]
 [ 23  75  86  74  63]]


<h5><center > Reshaping array

In [40]:
import random
list1 = [random.randint(10,99) for _ in range(12)]

arr1 = np.array(list1)
print(arr1)

arr_changed = arr1.reshape(6,2)
print("Array with shape of 6x2 \n",arr_changed)

arr_2D = arr1.reshape(4,3)
print("Array with shape of 4x3 \n",arr_2D)

arr_3D = arr1.reshape(2,3,2)
print("1D array converted to 3D \n", arr_3D)

[28 46 39 53 88 83 34 57 35 86 92 82]
Array with shape of 6x2 
 [[28 46]
 [39 53]
 [88 83]
 [34 57]
 [35 86]
 [92 82]]
Array with shape of 4x3 
 [[28 46 39]
 [53 88 83]
 [34 57 35]
 [86 92 82]]
1D array converted to 3D 
 [[[28 46]
  [39 53]
  [88 83]]

 [[34 57]
  [35 86]
  [92 82]]]


In [41]:
arr_3D.flatten()

array([28, 46, 39, 53, 88, 83, 34, 57, 35, 86, 92, 82])

In [42]:
arr_3D.reshape(-1)              # automatically reshapes the array based on other dimension

array([28, 46, 39, 53, 88, 83, 34, 57, 35, 86, 92, 82])

In [43]:
arr_3D.reshape(2, -1)           # it gets to know that it has to be 2D array , rest it doesn't care 

array([[28, 46, 39, 53, 88, 83],
       [34, 57, 35, 86, 92, 82]])

<h5><center> Spliting the array

In [46]:
arr1 = np.random.randint(1,99,size = 12)
print(arr1)

[74 58 39  3  7 25 42 10 33 54 66 39]


In [50]:
split_arr = np.split(arr1 , 6)
print("Split array into 6 parts")
print(split_arr)

Split array into 6 parts
[array([74, 58], dtype=int32), array([39,  3], dtype=int32), array([ 7, 25], dtype=int32), array([42, 10], dtype=int32), array([33, 54], dtype=int32), array([66, 39], dtype=int32)]


In [54]:
arr2D = arr1.reshape(4,3)
split_2D = np.split(arr2D ,3 , axis =1)         # along columns
print("Og 2D array: ", arr2D)
print("Split 2D array along column:", split_2D)

Og 2D array:  [[74 58 39]
 [ 3  7 25]
 [42 10 33]
 [54 66 39]]
Split 2D array along column: [array([[74],
       [ 3],
       [42],
       [54]], dtype=int32), array([[58],
       [ 7],
       [10],
       [66]], dtype=int32), array([[39],
       [25],
       [33],
       [39]], dtype=int32)]


In [57]:
split_2d1 = np.split(arr2D, 1, axis = 0)        # along row ( cannot split cpz it has odd number of elements in a row)
print("Split 2D array along Row:", split_2d1)

Split 2D array along Row: [array([[74, 58, 39],
       [ 3,  7, 25],
       [42, 10, 33],
       [54, 66, 39]], dtype=int32)]


In [60]:
# to print it in cleaner way , we can use for loop
for i in split_2D:
    print(i) 

[[74]
 [ 3]
 [42]
 [54]]
[[58]
 [ 7]
 [10]
 [66]]
[[39]
 [25]
 [33]
 [39]]


<h5><center> Statistical Operations

In [64]:
arr_2D

array([[28, 46, 39],
       [53, 88, 83],
       [34, 57, 35],
       [86, 92, 82]])

In [70]:
# Mean
mean_all = np.mean(arr_2D)
print('mean of all elements:',mean_all)

mean_axis0= np.mean(arr_2D, axis= 0)                    # column
print('Mean along the columns', mean_axis0)

mean_axis1 = np.mean(arr_2D , axis =1)                  # row
print('Mean along rows', np.round(mean_axis1,2))        # rounding up the values to 2 decimal places

mean of all elements: 60.25
Mean along the columns [50.25 70.75 59.75]
Mean along rows [37.67 74.67 42.   86.67]


In [71]:
# Median
median_all = np.median(arr_2D)
median_axis0 = np.median(arr_2D ,axis = 0)
median_axis1 = np.median(arr_2D ,axis = 1)

print("Median of all elements:", median_all)
print("Median along columns:", median_axis0)
print("Median along rows:", median_axis1)


Median of all elements: 55.0
Median along columns: [43.5 72.5 60.5]
Median along rows: [39. 83. 35. 86.]


In [74]:
# Standard Deviation
std_dev = np.std(arr_2D, axis = 0)
print(np.round(std_dev,2))

[22.61 19.69 22.8 ]


In [76]:
# Min and Max
min_all = np.min(arr_2D)
min_axis0 = np.min(arr_2D, axis= 0)
max_axis1 =np.max(arr_2D , axis= 1)

print("minimum element of all:",min_all)
print("minimum of array along column", min_axis0)
print("maximum of all elements along row:", max_axis1)

minimum element of all: 28
minimum of array along column [28 46 35]
maximum of all elements along row: [46 88 57 92]


In [77]:
# sum 
sum_all = np.sum(arr_2D)
sum_axis0 = np.sum(arr_2D, axis= 0)
sum_axis1 =np.sum(arr_2D , axis= 1)

print("sum of all element :",sum_all)
print("sum of array along column", sum_axis0)
print("sum of all elements along row:", sum_axis1)

sum of all element : 723
sum of array along column [201 283 239]
sum of all elements along row: [113 224 126 260]


In [79]:
print(arr1)
print(np.percentile(arr1,25))          #first quartile
print(np.percentile(arr1,50))           # median
print(np.percentile(arr1,75))           # 3rd quartile

[74 58 39  3  7 25 42 10 33 54 66 39]
21.25
39.0
55.0


<h5><center > Creating array

In [ ]:
# zeros 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))                             # By default data type is float

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [86]:
np.ones((3,3), dtype =str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [ ]:
np.full(5,7)                # (shape , fill_value)

array([7, 7, 7, 7, 7])

In [88]:
np.full((3,3),-1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [89]:
np.full((2,3,2), 3.14)

array([[[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]]])

In [92]:
# eye
id_3x3 = np.eye(3)
print("3X3 identity matrix is:\n", id_3x3)


3X3 identity matrix is:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [93]:
id_3x4 = np.eye(3,4)
print("3X4 identity matrix is: \n",id_3x4)

3X4 identity matrix is: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [95]:
id_shift = np.eye(4,4,k=1)
print("4X4 Identity Matrix with shifted diagonal: \n",id_shift)

4X4 Identity Matrix with shifted diagonal: 
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [100]:
id_shift1 = np.eye(4, k=-1, dtype=int)                                         # by default k = 0
print("4X4 Identity Matrix with diagonal shifted down: \n", id_shift1)

4X4 Identity Matrix with diagonal shifted down: 
 [[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [ ]:
# arange()              ( creates 1D array, does not creates 2D or 3D directly)
array1 = np.arange(10)
print("array with default start and stop:",array1)

array with default start and step: [0 1 2 3 4 5 6 7 8 9]


In [98]:
array2 = np.arange(3,13)
print("array with specified start and stop:",array2)

array with specified start and stop: [ 3  4  5  6  7  8  9 10 11 12]


In [99]:
array3 = np.arange(0,11,2)
print("array with specified start ,stop and step:",array3)

array with specified start ,stop and step: [ 0  2  4  6  8 10]


In [ ]:
# random.random 
array_1d = np.random.random(5)                          # chooses values between 0 and 1
print("1D array: \n",array_1d)

array_2d = np.random.random((2,3))                      # (2,3) is the shape
print("2D array: \n",array_2d)

array_2d = np.random.randint(10,100,size =(3,3))                      # (3,3) is the shape
print("2D random array (10,100): \n",array_2d)


1D array: 
 [0.93245972 0.6977365  0.90626333 0.42400841 0.68180817]
2D array: 
 [[0.88409372 0.71025923 0.56097211]
 [0.06328417 0.28454409 0.41346441]]
2D random array (10,100): 
 [[38 94 71]
 [53 38 30]
 [56 96 42]]


In [105]:
# linspace
array1 = np.linspace(0,1,5)
print("Array with 5 even spaced values from 0 and 1: \n",array1)

array2 = np.linspace(0,5,10)
print("\nArray with 10 evenly spaced values from 0 to 5: \n",array2)

Array with 5 even spaced values from 0 and 1: 
 [0.   0.25 0.5  0.75 1.  ]

Array with 10 evenly spaced values from 0 to 5: 
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
